export const skills = [
    { src: "/skills/js_logo.svg", title: "Javascript", categories: ["frontend", "backend"] },
    { src: "/skills/typescript_logo.svg", title: "Typescript", categories: ["frontend", "backend"] },
    { src: "/skills/node_logo.svg", title: "Node.js", categories: ["backend"] },
    { src: "/skills/nestjs_logo.svg", title: "NestJS", categories: ["backend"] },
    { src: "/skills/express_logo.svg", title: "Express.js", categories: ["backend"] },
    { src: "/skills/jest_logo.svg", title: "Jest", categories: ["backend", "frontend"] },
    { src: "/skills/php_logo.svg", title: "PHP", categories: ["backend"] },
    { src: "/skills/symfony_logo.svg", title: "Symfony", categories: ["backend"] },
    { src: "/skills/html_logo.svg", title: "HTML", categories: ["frontend"] },
    { src: "/skills/css_logo.svg", title: "CSS", categories: ["frontend"] },
    { src: "/skills/tailwind_logo.svg", title: "Tailwind CSS", categories: ["frontend"] },
    { src: "/skills/nextjs_logo.svg", title: "Next.js", categories: ["frontend", "backend"] },
    { src: "/skills/react_logo.svg", title: "React", categories: ["frontend"] },
    { src: "/skills/angular_logo.svg", title: "Angular", categories: ["frontend"] },
    { src: "/skills/jquery_logo.svg", title: "jQuery", categories: ["frontend"] },
    { src: "/skills/react_query_logo.svg", title: "React Query", categories: ["frontend"] },
    { src: "/skills/framermotion_logo.webp", title: "Framer Motion", categories: ["frontend"] },
    { src: "/skills/mysql_logo.svg", title: "MySQL", categories: ["databases"] },
    { src: "/skills/mongo_logo.svg", title: "MongoDB", categories: ["databases"] },
    { src: "/skills/prisma_logo.svg", title: "Prisma", categories: ["databases"] },
    { src: "/skills/firebase_logo.svg", title: "Firestore", categories: ["databases"] },
    { src: "/skills/git_logo.svg", title: "Git", categories: ["operations"] },
    { src: "/skills/gitlab_logo.svg", title: "GitLab CI", categories: ["operations"] },
    { src: "/skills/github_logo.svg", title: "GitHub Actions", categories: ["operations"] },
    { src: "/skills/docker_logo.svg", title: "Docker", categories: ["operations"] },
    { src: "/skills/k8s_logo.svg", title: "Kubernetes", categories: ["operations"] },
    { src: "/skills/helm_logo.svg", title: "Helm", categories: ["operations"] },
    { src: "/skills/aws_logo.svg", title: "AWS", categories: ["operations"] },
    { src: "/skills/nginx_logo.svg", title: "Nginx", categories: ["operations"] },
    { src: "/skills/apache_logo.svg", title: "Apache", categories: ["operations"] },
    { src: "/skills/bash_logo.svg", title: "Bash", categories: ["operations"] },
    { src: "/skills/vercel_logo.svg", title: "Vercel", categories: ["operations"] },
];

