export const skills = [
    { src: "/skills/html_logo.svg", title: "HTML", categories: ["frontend"] },
    { src: "/skills/css_logo.svg", title: "CSS", categories: ["frontend"] },
    { src: "/skills/js_logo.svg", title: "Javascript", categories: ["frontend"] },
    { src: "/skills/typescript_logo.svg", title: "Typescript", categories: ["frontend"] },
    { src: "/skills/tailwind_logo.svg", title: "Tailwind CSS", categories: ["frontend"] },
    { src: "/skills/nextjs_logo.svg", title: "Next.js", categories: ["frontend"] },
    { src: "/skills/react_logo.svg", title: "React", categories: ["frontend"] },
    { src: "/skills/angular_logo.svg", title: "Angular", categories: ["frontend"] },
    { src: "/skills/jquery_logo.svg", title: "jQuery", categories: ["frontend"] },
    { src: "/skills/react_query_logo.svg", title: "React Query", categories: ["frontend"] },
    { src: "/skills/framermotion_logo.webp", title: "Framer Motion", categories: ["frontend"] },
    { src: "/skills/php_logo.svg", title: "PHP", categories: ["backend"] },
    { src: "/skills/symfony_logo.svg", title: "Symfony", categories: ["backend"] },
    { src: "/skills/laravel_logo.svg", title: "Laravel", categories: ["backend"] },
    { src: "/skills/node_logo.svg", title: "Node.js", categories: ["backend"] },
    { src: "/skills/express_logo.svg", title: "Express.js", categories: ["backend"] },
    { src: "/skills/mysql_logo.svg", title: "MySQL", categories: ["backend"] },
    { src: "/skills/firebase_logo.svg", title: "Firestore", categories: ["backend"] },
    { src: "/skills/firebase_logo.svg", title: "Firebase", categories: ["backend"] },
    { src: "/skills/vercel_logo.svg", title: "Vercel", categories: ["devops"] },
    { src: "/skills/git_logo.svg", title: "Git", categories: ["devops"] },
    { src: "/skills/gitlab_logo.svg", title: "GitLab", categories: ["devops"] },
    { src: "/skills/github_logo.svg", title: "GitHub Actions", categories: ["devops"] },
    { src: "/skills/docker_logo.svg", title: "Docker", categories: ["devops"] },
    { src: "/skills/bash_logo.svg", title: "Bash", categories: ["devops"] },
];

